apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecr-creds.fullname" . }}
  labels:
    {{- include "ecr-creds.labels" . | nindent 4 }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretAccessKey }}
